project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"
    - "!ME*"
    - "!Dissertation_Proposal"


exclude: ["*.rds","*.tex","*.csl","*.bib","docs*","404.html","_old*","out.bib",
"*.pdf","*.R",".obsidian","Rproj","R","Bib","_site","exp","HTW_Analysis/**","*HTW_Modelling/**","Motivated*","Manuscript*"]

# Exclude all files in HTW_Analysis folder, recursively

book:
  title: "Dissertation"
  reader-mode: true
  chapters:
    - index.md
    - outline.qmd
    - IGAS.qmd
    - HTW.qmd
    - Discussion.qmd

   

# book:
#   title: "Dissertation"
#   navbar:
#     left:
#       - text: Outline
#         file: Outline.qmd
      



format:
  html:
    theme:
      - cosmo
      - style.scss
    code-link: true
