project:
  type: website
  output-dir: docs
  preview:
    port: 4205
  render:
    - "*.qmd"
    - "!_*"
    - "!ME*"
    - "!_Dissertation_Proposal"
    - "!Manuscript/"
    - "!Scratch/"
    - "!Sections/docx_test.qmd"
    - "!Presentation/slides2.qmd"

  resources: 
    - "Manuscript/output/"
    - "Manuscript/Assets/"
    - "Manuscript/Assets/figs/"


exclude: ["*.rds","*.tex","docs*","404.html","_old*","out.bib",
"*.pdf","*.R",".obsidian","Rproj","R","Bib","_site","exp","HTW_Analysis/**","*HTW_Modelling/**","Motivated*"]

# Exclude all files in HTW_Analysis folder, recursively



website:
  title: "Dissertation"
  repo-url: https://github.com/tegorman13/Dissertation
  site-url: "https://tegorman13.github.io/Dissertation/"
  reader-mode: true
  page-navigation: false
  sidebar:
    style: "docked"
    border: false
    collapse-level: 2
    pinned: false
    target: _blank
    tools:
    - icon: github
      href: https://github.com/tegorman13/Dissertation
    contents:
      #- index.qmd
      #- text: "---"
      - paper.qmd
      - Sections/Appendix/Full_Appendix.qmd
      - text: "---"
      - text: "Slides"
        href: Presentation/slides.qmd
      - text: "---"
      - text: "Full Dissertation w/Code"
        href: Sections/full.qmd
      #- text: "---"
      # - text: Intro
      #   href: Sections/Introduction.qmd
      - Sections/IGAS.qmd
      - Sections/HTW.qmd
      #- Sections/Discussion.qmd

format:
  html:
    theme:
      - cosmo
      - Assets/Style/style.scss
    css: Assets/Style/calloutTG.css
    code-link: false
    code-summary: "Display code"
    html-math-method: mathjax
    citations-hover: true
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.tegorman13.github.io/Dissertation\/custom'


bibliography: [Assets/Bib/Dissertation.bib]
csl: Assets/Bib/apa.csl

execute:
  freeze: auto



# book:
#   title: "Dissertation"
#   reader-mode: true
#   chapters:
#     - index.md
#     - plan.qmd
#     - outline.qmd
#     - Introduction.qmd
#     - IGAS.qmd
#     - HTW.qmd
#     - Discussion.qmd

   

# book:
#   title: "Dissertation"
#   navbar:
#     left:
#       - text: Outline
#         file: Outline.qmd
      



