project:
  type: website
  output-dir: docs
  preview:
    port: 4205
  render:
    - "*.qmd"
    - "!ME*"
    - "!Dissertation_Proposal"


exclude: ["*.rds","*.tex","*.csl","*.bib","docs*","404.html","_old*","out.bib",
"*.pdf","*.R",".obsidian","Rproj","R","Bib","_site","exp","HTW_Analysis/**","*HTW_Modelling/**","Motivated*","Manuscript*"]

# Exclude all files in HTW_Analysis folder, recursively



website:
  title: "Dissertation"
  repo-url: https://github.com/tegorman13/Dissertation
  site-url: "https://tegorman13.github.io/Dissertation/"
  reader-mode: true
  page-navigation: true
  sidebar:
    style: "docked"
    border: false
    collapse-level: 2
    pinned: false
    contents:
      - index.md
      - plan.qmd
      - outline.qmd
      - Introduction.qmd
      - IGAS.qmd
      - HTW.qmd
      - Discussion.qmd

format:
  html:
    theme:
      - cosmo
      - style.scss
    code-link: false
    html-math-method: mathjax
    citations-hover: false


bibliography: [Bib/IGAS.bib]
csl: Bib/apa7.csl




# book:
#   title: "Dissertation"
#   reader-mode: true
#   chapters:
#     - index.md
#     - plan.qmd
#     - outline.qmd
#     - Introduction.qmd
#     - IGAS.qmd
#     - HTW.qmd
#     - Discussion.qmd

   

# book:
#   title: "Dissertation"
#   navbar:
#     left:
#       - text: Outline
#         file: Outline.qmd
      



