project:
  title: "Manuscript"
  render: 
  - "manuscript.qmd"
  - "manuscript_full.qmd"

execute: 
  warning: false
  eval: true
  include: true
  freeze: auto


bibliography: [../Assets/Bib/Dissertation.bib]
csl: ../Assets/Bib/apa.csl

profile:
  group: 
    - [plain, nice,thesis, ms, md]

# execute:
#   freeze: auto