project:
  title: "Manuscript"

execute: 
  warning: false
  eval: true
  include: true
  freeze: auto


bibliography: [../Assets/Bib/Dissertation.bib]
csl: ../Assets/Bib/apa7.csl

profile:
  group: 
    - [plain, nice, thesis, ms, md]

# execute:
#   freeze: auto