project:
  title: "Manuscript"

  render: 
    - "*.qmd"
   #- "!submissions/*.qmd"
    - "!test_igas.qmd"

bibliography: [../Assets/Bib/htw.bib]
csl: ../Assets/Bib/apa7.csl

profile: 
  default: nice
